name: scrape_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil:
  camera:
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  provider: ^6.1.5+1
  image_picker:
  google_mlkit_object_detection: ^0.13.0
  google_mlkit_image_labeling:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
